name: JabBukkit
main: de.odie.JabBukkit.JabBukkit
version: 0.4b
description: A Simple XMPP Plugin, that sends all Chat events to a specific Jabber Account
author: odie
commands:
   jb:
      description: This is the basic plugin command.
      usage: /<command>
   jbadmin:
      description: This is the basic plugin administration command.
      permission: jabbukkit.admin
      usage: |
       /<command> (reload | adduser | setstatus)
       /<command> reload - Reloads config.yml and reconnects XMPP
       /<command> adduser (username) (jid) - Adds (username) with (jid) to config.yml
       /<command> setstatus Hi there - Sets the online status message to "Hi there"'